### ISSUE TITLE
allow the exporter to use github apps for authentication

### ISSUE THREAD

**Issue by oneubauer** [Spendesk/github-actions-exporter#24]
Hello!

Thanks for the exporter. We needed the ability to use github apps for authentication instead of PATs so I've submitted a PR:

https://github.com/Spendesk/github-actions-exporter/pull/22

**Comment by neillturner** [comment]
my PR https://github.com/Spendesk/github-actions-exporter/pull/21 also does the same thing as well as supplies a helm chart. don't really care who's code we use. it would be nice to have a public helm chart.

**Comment by oneubauer** [comment]
Awesome. Happy to have mine dropped in lieu of yours. I'll leave it to the team to do so!
Thanks for the chart!

**Comment by Labbs** [comment]
Released : [v1.8.1](https://github.com/Spendesk/github-actions-exporter/releases/tag/v1.8.1)
