### ISSUE TITLE
doc: note scope

### ISSUE THREAD

**Issue by srl295** [Spendesk/github-actions-exporter#5]
should note:  `public_repo` scope is needed for public repos, and `repo` for private repos.

more: https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#workflow-runs

**Comment by Labbs** [comment]
hello, ok I check how fix that.

**Comment by Labbs** [comment]
hello, I added an information in the readme for this part.
You just need to update the token scope to add `public_repo`.

**Comment by srl295** [comment]
Looks good, so this is:
Fixed by 411f15501feb426263fb26787469e5c1419cde01
