### ISSUE TITLE
bug: workflow_id is missing

### ISSUE THREAD

**Issue by srl295** [Spendesk/github-actions-exporter#8]
- github_job{event="push",head_branch="master",head_sha="0144e8d5a573c5ea9a5b1d92f597e3318310fb6c",id="497499385",instance="localhost:9183",job="github_actions",node_id="MDExOldvcmtmbG93UnVuNDk3NDk5Mzg1",repo="unicode-org/cldr",run_number="1120",status="completed"} | 1
- github_job{event="push",head_branch="master",head_sha="0144e8d5a573c5ea9a5b1d92f597e3318310fb6c",id="497499386",instance="localhost:9183",job="github_actions",node_id="MDExOldvcmtmbG93UnVuNDk3NDk5Mzg2",repo="unicode-org/cldr",run_number="660",status="completed"} | 1

I just realized that the `workflow_id` is missing.  So as you see above, I get two duplicate entries.

Ideally the workflow's name would be given, not just the numeric id (which isn't very helpful)

**Comment by srl295** [comment]
should use this API to get and cache a list of the repo's workflows: <https://docs.github.com/en/rest/reference/actions#list-repository-workflows>

**Comment by Labbs** [comment]
I'll look at how to implement this.

**Comment by Labbs** [comment]
```
github_job{event="push",head_branch="master",head_sha="5ab74d5af9eb533e6564996bde43528175092591",id="63984311",node_id="MDExOldvcmtmbG93UnVuNjM5ODQzMTE=",repo="Spendesk/github-actions-exporter",run_number="3",status="completed",workflow="Release",workflow_id="470256"} 1
```
We have `workflow_id` and `workflow`.
It's not released yet.

**Comment by Labbs** [comment]
Hello, It's fixed with the latest version.
